development:
  adapter: mysql
  encoding: utf8
  database: pm_development
  username: root
  password: 123
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: pm_test
  username: root
  password: 123
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: pm_production
  username: root
  password: 123
  host: localhost
