development:
  adapter: mysql
  encoding: utf8
  database: pm_development
  username: root
  password: 123
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: pm_test
  username: root
  password: 123
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: th30642_pm
  username: th30642_tiago
  password: 123
  host: bm8.webservidor.net
